fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

login:
    path:     /
    defaults: { _controller: AppBundle:Security:login }

user_register:
    path:     /registration
    defaults: { _controller: AppBundle:Registration:register }

user_login_check:
    path:    /login/checker
    defaults: { _controller: AppBundle:Security:check }

dashboard:
    path:    /dashboard
    defaults: { _controller: AppBundle:Default:index}